// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/accounting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounting">> = Specific
  const handler = {} as typeof import("../../../src/app/accounting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../../src/app/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/cashflow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cashflow">> = Specific
  const handler = {} as typeof import("../../../src/app/cashflow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/freedom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/freedom">> = Specific
  const handler = {} as typeof import("../../../src/app/freedom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/goals">> = Specific
  const handler = {} as typeof import("../../../src/app/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/liabilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/liabilities">> = Specific
  const handler = {} as typeof import("../../../src/app/liabilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/mentors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentors">> = Specific
  const handler = {} as typeof import("../../../src/app/mentors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/timemachine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/timemachine">> = Specific
  const handler = {} as typeof import("../../../src/app/timemachine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/trust/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trust">> = Specific
  const handler = {} as typeof import("../../../src/app/trust/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/accounting/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accounting">> = Specific
  const handler = {} as typeof import("../../../src/app/api/accounting/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/action/parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/action/parse">> = Specific
  const handler = {} as typeof import("../../../src/app/api/action/parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/bank/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/api/bank/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/bank/exchange/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank/exchange">> = Specific
  const handler = {} as typeof import("../../../src/app/api/bank/exchange/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/bank/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank/link">> = Specific
  const handler = {} as typeof import("../../../src/app/api/bank/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/bank/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bank/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/bank/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/sync-banks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sync-banks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/sync-banks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documents/mappings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/mappings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documents/mappings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documents/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documents/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documents/proposals/candidates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/proposals/candidates">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documents/proposals/candidates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documents/proposals/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/proposals/link">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documents/proposals/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documents/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/proposals">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documents/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documents/raw/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents/raw">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documents/raw/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/documents">> = Specific
  const handler = {} as typeof import("../../../src/app/api/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/mentor/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mentor/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/mentor/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/mentor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mentor">> = Specific
  const handler = {} as typeof import("../../../src/app/api/mentor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/vault/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vault">> = Specific
  const handler = {} as typeof import("../../../src/app/api/vault/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/basiq/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/basiq">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/basiq/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/plaid/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/plaid">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/plaid/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
