// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/accounting" | "/admin" | "/assets" | "/cashflow" | "/freedom" | "/goals" | "/liabilities" | "/login" | "/mentors" | "/portfolio" | "/privacy" | "/timemachine" | "/trust"
type AppRouteHandlerRoutes = "/api/accounting" | "/api/action/parse" | "/api/ai/status" | "/api/bank/callback" | "/api/bank/exchange" | "/api/bank/link" | "/api/bank/status" | "/api/cron/sync-banks" | "/api/documents" | "/api/documents/mappings" | "/api/documents/pdf" | "/api/documents/proposals" | "/api/documents/proposals/candidates" | "/api/documents/proposals/link" | "/api/documents/raw" | "/api/mentor" | "/api/mentor/profile" | "/api/vault" | "/api/webhooks/basiq" | "/api/webhooks/plaid" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/accounting": {}
  "/admin": {}
  "/api/accounting": {}
  "/api/action/parse": {}
  "/api/ai/status": {}
  "/api/bank/callback": {}
  "/api/bank/exchange": {}
  "/api/bank/link": {}
  "/api/bank/status": {}
  "/api/cron/sync-banks": {}
  "/api/documents": {}
  "/api/documents/mappings": {}
  "/api/documents/pdf": {}
  "/api/documents/proposals": {}
  "/api/documents/proposals/candidates": {}
  "/api/documents/proposals/link": {}
  "/api/documents/raw": {}
  "/api/mentor": {}
  "/api/mentor/profile": {}
  "/api/vault": {}
  "/api/webhooks/basiq": {}
  "/api/webhooks/plaid": {}
  "/assets": {}
  "/auth/callback": {}
  "/cashflow": {}
  "/freedom": {}
  "/goals": {}
  "/liabilities": {}
  "/login": {}
  "/mentors": {}
  "/portfolio": {}
  "/privacy": {}
  "/timemachine": {}
  "/trust": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
